=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/lib/org/jext/xproperties.dtd
<!ELEMENT xproperties (#PCDATA | property)* >
  <!ELEMENT property EMPTY >
    <!ATTLIST property name CDATA #REQUIRED >
    <!ATTLIST property value CDATA #REQUIRED >

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/plugins/KLNF/KLNF.props.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xproperties SYSTEM "xproperties.dtd" >

<xproperties>
  <property name="plugin.KLNFPlugin.name" value="KLNF" />
  <property name="plugin.KLNFPlugin.author" value="Romain Guy" />
  <property name="plugin.KLNFPlugin.version" value="2.0.1" />
  <property name="plugin.KLNFPlugin.depend.0" value="jext 03.00.00.01" />

  <property name="options.klnf.label" value="Kunststoff LnF" />
  <property name="klnf.enable.label" value="Enable Kunststoff Look and Feel" />
  <property name="klnf.enable" value="off" />
</xproperties>

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/plugins/Php/src/PHPPlugin.props.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xproperties SYSTEM "xproperties.dtd" >
<xproperties>
 <property name="plugin.PHPPlugin.name" value="PHP" />
 <property name="plugin.PHPPlugin.author" value="Nicolas Thouvenin" />
 <property name="plugin.PHPPlugin.version" value="1.1" />
 <property name="PHP_menu" value="phpbrowse - phpquickopen - phpindenter  phpblocindenter - phpbeautifier phpblocbeautifier - phpcomplete" />
 <property name="PHP_menu.label" value="PHP" />

 <property name="plugin.PHPPlugin.modes" value="php3" />

  <property name="phpbrowse.label" value="Source Browser" />
  <property name="phpbrowse.shortcut" value="C+p C+b" />

 <property name="phpindenter.label" value="Indent File" />

 <property name="phpblocindenter.label" value="Indent Block" />
 <property name="phpblocindenter.shortcut" value="C+p C+i" />

 <property name="phpbeautifier.label" value="Beautifier File" />

 <property name="phpblocbeautifier.label" value="Beautifier Block" />
 <property name="phpblocbeautifier.shortcut" value="C+p C+p" />

 <property name="phpquickopen.label" value="Quick Open" />
 <property name="phpquickopen.shortcut" value="C+p C+o" />

 <property name="phpcomplete.label" value="Complete Function" />
 <property name="phpcomplete.shortcut" value="C+p C+/" />
</xproperties>

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/lib/org/jext/jext-keys.props.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xproperties SYSTEM "xproperties.dtd" >

<xproperties>
  <!-- ============================================================ -->
  <!-- FILE MENU SHORTCUTS                                          -->
  <!-- ============================================================ -->
  <property name="new.shortcut" value="C+n" />
  <property name="open.shortcut" value="C+o" />
  <property name="close.shortcut" value="C+w" />
  <property name="open.shortcut" value="C+o" />
  <property name="save.shortcut" value="C+s" />
  <property name="save_all.shortcut" value="CS+s" />
  <property name="save_as.shortcut" value="CA+s" />
  <property name="print.shortcut" value="C+p" />
  <property name="quit.shortcut" value="C+q" />

  <!-- ============================================================ -->
  <!-- EDIT MENU SHORTCUTS                                          -->
  <!-- ============================================================ -->
  <property name="undo.shortcut" value="C+z" />
  <property name="redo.shortcut" value="C+y" />
  <property name="copy.shortcut" value="C+c" />
  <property name="append_copy.shortcut" value="CA+c" />
  <property name="cut.shortcut" value="C+x" />
  <property name="append_cut.shortcut" value="CA+x" />
  <property name="paste.shortcut" value="C+v" />
  <property name="filtered_paste.shortcut" value="CA+v" />
  <property name="reverse_paste.shortcut" value="CS+v" />
  <property name="select_all.shortcut" value="C+a" />
    <!-- ========================================================== -->
    <!-- ANCHOR SUBMENU SHORTCUTS                                   -->
    <!-- ========================================================== -->
    <property name="set_anchor.shortcut" value="C+e C+s" />
    <property name="goto_anchor.shortcut" value="C+e C+g" />
    <property name="exchange_anchor.shortcut" value="C+e C+x" />
    <!-- ========================================================== -->
    <!-- SOURCE CODE SUBMENU SHORTCUTS                              -->
    <!-- ========================================================== -->
    <property name="right_indent.shortcut" value="A+RIGHT" />
    <property name="left_indent.shortcut" value="A+LEFT" />
    <property name="find_matching_bracket.shortcut" value="C+m" />
    <!-- ========================================================== -->
    <!-- TEXT SUBMENU SHORTCUTS                                     -->
    <!-- ========================================================== -->
    <property name="to_upper_case.shortcut" value="C+e C+u" />
    <property name="to_lower_case.shortcut" value="C+e C+l" />
    <property name="join_lines.shortcut" value="C+e C+j" />
    <property name="transpose_lines.shortcut" value="C+e C+t" />
    <property name="complete_word.shortcut" value="C+SPACE" />
    <property name="complete_word_all.shortcut" value="CS+SPACE" />
    <!-- ========================================================== -->
    <!-- ONE CLICK! SUBMENU SHORTCUTS                               -->
    <!-- ========================================================== -->
    <property name="end_one_click.shortcut" value="C+e C+e" />
  <property name="goto_line.shortcut" value="C+g" />
  <property name="delete_line.shortcut" value="C+d" />
  <property name="insert_date.shortcut" value="C+i" />

  <!-- ============================================================ -->
  <!-- SEARCH MENU SHORTCUTS                                        -->
  <!-- ============================================================ -->
  <property name="find.shortcut" value="C+f" />
  <property name="replace.shortcut" value="C+r" />
  <property name="find_next.shortcut" value="F3" />
  <property name="find_all.shortcut" value="C+F3" />
  <property name="replace_next.shortcut" value="F4" />
  <property name="replace_selection.shortcut" value="C+F4" />

  <!-- ============================================================ -->
  <!-- SCRIPTS MENU SHORTCUTS                                       -->
  <!-- ============================================================ -->
  <property name="python_execute.shortcut" value="F5" />
  <property name="python_run_script.shortcut" value="CA+F5" />
  <property name="python_log_window.shortcut" value="CS+F5" />
  <property name="split_editor.shortcut" value="F6" />
  <property name="trigger_left_pane.shortcut" value="F7" />
  <property name="trigger_top_pane.shortcut" value="F8" />

  <!-- ============================================================ -->
  <!-- JEXT MENU SHORTCUTS                                          -->
  <!-- ============================================================ -->
  <property name="about.shortcut" value="F1" />
  <property name="about_plugins.shortcut" value="F2" />

  <!-- ============================================================ -->
  <!-- SHORTCUTS                                                    -->
  <!-- ============================================================ -->
  <property name="next_tab.shortcut" value="C+TAB" />
  <property name="previous_tab.shortcut" value="CS+TAB" />
</xproperties>

<!-- End of jext-keys.props.xml -->

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/plugins/FindAll/FindAll.props.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xproperties SYSTEM "xproperties.dtd" >

<xproperties>
  <property name="plugin.FindAllPlugin.name" value="FindAll" />
  <property name="plugin.FindAllPlugin.author" value="Grant Stead" />
  <property name="plugin.FindAllPlugin.version" value="1.0" />

  <property name="FindAll.title" value="FindAll" />
    
  <property name="FindAllAction.label" value="FindAll" />
  <property name="FindAllAction.shortcut" value="C+F3" />
  <property name="find.all.unHighlight" value="Unhighlight" />
</xproperties>

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/bin/WheelMouse.props.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xproperties SYSTEM "xproperties.dtd" >

<xproperties>
  <property name="plugin.WheelMousePlugin.name" value="Wheel Mouse" />
  <property name="plugin.WheelMousePlugin.author" value="Scott Wyatt ported by Barranger Ridler" />
  <property name="plugin.WheelMousePlugin.version" value="1.0" />
  <property name="plugin.WheelMousePlugin.depend.0" value="os Windows" />
  <property name="plugin.WheelMousePlugin.depend.1" value="deprecateJDK 1.4" />

  <property name="options.wheelmouse.imgenabled" value="Enable backing store to prevent flashing" />
  <property name="options.wheelmouse.lineenabled" value="Specify wheel mouse lines increment" />
  <property name="options.wheelmouse.line" value="Line increment:" />
</xproperties>

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/bin/KeystrokeRecorder.props.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xproperties SYSTEM "xproperties.dtd" >
<xproperties>
  <property name="plugin.KeystrokeRecorderPlugin.name" value="Keystroke Recorder" />
  <property name="plugin.KeystrokeRecorderPlugin.author" value="James Kolean, Matt Benson" />
  <property name="plugin.KeystrokeRecorderPlugin.version" value="0.2" />
  <property name="plugin.KeystrokeRecorderPlugin.depend.0" value="jext 02.10.00.00" />

  <property name="keystroke_recorder.menu" value="keystroke_recorder.menu.record keystroke_recorder.menu.stop keystroke_recorder.menu.play" />
  <property name="keystroke_recorder.menu.label" value="Keystroke Recorder" />
  <property name="keystroke_recorder.menu.record.label" value="Record" />
  <property name="keystroke_recorder.menu.stop.label" value="Stop" />
  <property name="keystroke_recorder.menu.play.label" value="Play" />
  <property name="keystroke_recorder.menu.play.shortcut" value="CA+ENTER" />
  <property name="keystroke_recorder.debug" value="off" />

</xproperties>

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/bin/XMLBrowse.props.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xproperties SYSTEM "xproperties.dtd" >

<xproperties>
  <property name="plugin.XMLBrowsePlugin.name" value="XML Browse" />
  <property name="plugin.XMLBrowsePlugin.author" value="Romain Guy" />
  <property name="plugin.XMLBrowsePlugin.version" value="1.0" />

  <property name="plugin.XMLBrowsePlugin.modes" value="html" />

  <property name="XML_menu" value="xmlbrowse" />
  <property name="XML_menu.label" value="XML" />
  <property name="xmlbrowse.label" value="XML Browser" />
</xproperties>

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/bin/FindInFiles.props.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xproperties SYSTEM "xproperties.dtd" >
<xproperties>
  <property name="FindInFiles.label" value="Find In Files Window" />
  <property name="plugin.FindInFilesPlugin.name" value="Find In Files" />
  <property name="plugin.FindInFilesPlugin.author" value="James Kolean" />
  <property name="plugin.FindInFilesPlugin.version" value="0.1" />
  <property name="plugin.FindInFilesPlugin.depend.0" value="jext 02.10.00.00" />
  <property name="options.find_in_files.label" value="Find in Files" />
  <property name="findinfiles.title" value="Find In Files" />
  <property name="findinfiles.path.label" value="Directory:"/>
  <property name="findinfiles.path.tooltip" value="Directory to start searching in"/>
  <property name="findinfiles.filter.label" value="Filter:"/>
  <property name="findinfiles.filter.tooltip" value="File filter to restrict search. May use '?' and '*'. Example: '*.java'"/>
  <property name="findinfiles.pattern.label" value="Pattern:"/>
  <property name="findinfiles.pattern.tooltip" value="Pattern to match on"/>
  <property name="findinfiles.regexp.label" value="Regular Expression"/>
  <property name="findinfiles.regexp.tooltip" value="Treat pattern as a Regular Expression"/>
  <property name="findinfiles.searchsubdir.label" value="Search Subdirectories"/>
  <property name="findinfiles.searchsubdir.tooltip" value="Search this directory and all subdirectories"/>
  <property name="findinfiles.ignorecase.label" value="Ignore Case"/>
  <property name="findinfiles.ignorecase.tooltip" value="Search ignoring case"/>
  <property name="findinfiles.search.label" value="Search"/>
  <property name="findinfiles.msg.nomatch" value="No matches found."/>
  <property name="findinfiles.msg.nodir" value="Directory not found."/>
  <property name="findinfiles.msg.nofilesallowed" value="Directory not found, file found instead."/>
  <property name="findinfiles.useglob.label" value="Use Un*x glob instead of regular expression"/>
</xproperties>
