=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/dtd/xtiny-doc-page.dtd
<!ELEMENT xtiny-doc-page (paragraph+ | break | menu)* >
  <!ATTLIST xtiny-doc-page author CDATA #REQUIRED
                           update CDATA #REQUIRED
                           title CDATA #REQUIRED
                           name CDATA #REQUIRED
                           prev CDATA #IMPLIED
                           next CDATA #IMPLIED >

  <!-- Equivalent to CODE tag in HTML: code -->
  <!ELEMENT code (#PCDATA) >

  <!-- Equivalent to B tag in HTML: bold -->
  <!ELEMENT b (#PCDATA) >

  <!-- Equivalent to I tag in HTML: italic -->
  <!ELEMENT i (#PCDATA) >

  <!-- Equivalent to A tag in HTML: anchor -->
  <!ELEMENT a (#PCDATA) >
    <!ATTLIST a href CDATA #REQUIRED >

  <!ELEMENT menu (submenu | item)* >
    <!ATTLIST menu title CDATA #IMPLIED >

  <!ELEMENT submenu (item*) >
    <!ATTLIST submenu title CDATA #REQUIRED >

  <!ELEMENT item (#PCDATA) >
    <!ATTLIST item name CDATA #REQUIRED >

  <!-- A paragraph which can be titled -->
  <!ELEMENT paragraph (#PCDATA | b | i | a | code)* >
    <!ATTLIST paragraph title CDATA #IMPLIED >

  <!-- An horizontal rule -->
  <!ELEMENT break EMPTY >

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/xml-fr/jext-xinsert.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xtiny-doc-page SYSTEM "../dtd/xtiny-doc-page.dtd" >

<!--
  -
  - Jext documentation source document
  - Based on xtiny-doc DTD
  -
  - DTD:xtiny-doc and XSL:xtiny-doc
  - are (C)1999 Romain Guy
  -
  - Last updated: 09/30/2001 - 00:45:57
  -
  -->

<xtiny-doc-page author="Romain Guy"
           update="09/30/2001"
           name="Jext : XInsert"
           title="XInsert"
           prev="jext-console.html"
           next="jext-workspaces.html">

  <paragraph title="Présentation">
    L'interface par défaut de Jext montre un panneau d'onglets sur la gauche. Ce panneau contient un onglet
    nommé "XInsert". Un clic sur cet onglet affiche alors le <b>panneau XInsert</b> contenant lui même
    l'arbre nommé <b>XTree</b>. Cet arbre est dynamiquement construit depuis un ensemble de fichiers XML
    livrés avec Jext. Cependant, vous pouvez ajouter vos propres éléments dans cet arbre en créant vous
    même vos fichiers XInsert. Notez que les éléments affichés dans l'arbre dépendent du mode de coloration
    syntaxique sélectionné.
  </paragraph>
  <paragraph>
    XInsert est un moyen rapide pour ajouter du texte pré-tapé au sein de vos documents. Par exemple,
    le noeud "Licences" contient diverses licences pour vos programmes. Le XTree peut également contenir
    des scripts Dawn pouvant être exécutés comme des macros. Cette section est dédiée à l'utilisation du panneau
    XInsert et à la création de nouveaux fichiers XInsert.
  </paragraph>

  <paragraph title="Panneau XInsert">
    La mise en page du <b>panneau XInsert</b>  est très simple. En haut du panneau se trouvent trois boutons:
    <b>Déployer</b>, <b>Refermer</b> et <b>Recharger</b>. Le premier permet d'ouvrir tous les noeuds de l'arbre
    pour en voir le contenu. Le second réalise l'opération inverse. Enfin, le troisième bouton permet de
    reconstruire l'arbre. Ceci est très utilise lorsque vous créez vos propres fichiers XInsert: ainsi vous
    pouvez les tester sans relancer Jext.
  </paragraph>
  <paragraph>
    En bas du panneau se trouvent trois cases à cocher. La première, <b>Ajouter Saut de Ligne</b>,
    permet de rajouter un saut de ligne à la fin du texte inséré. La seconde, <b>Exécuter Scripts</b>, permet
    de lancer l'exécution des scripts contenus dans l'arbre lors d'un clic sur ceux-ci. Un script est
    représenté par un icone de couleur rouge. Si vous ne cochez pas la case, le contenu du script sera
    inséré dans le texte. Enfin, la dernière case à cocher, <b>Inclure Sélection</b>, permet de placer
    le texte sélectionné en un endroit donné d'un texte à insérer. Par exemple, si vous insérez la séquence
    <b>&lt;a href=""&gt;&lt;/a&gt;</b> et que vous avez sélectionné le texte "http://www.jext.org", vous
    obtiendrez: <b>&lt;a href="http://www.jext.org"&gt;&lt;/a&gt;</b>.
  </paragraph>
  <paragraph>
    La partie la plus importante du panneau reste cependant l'arbre. Le XTree contient un jeu de noeuds que
    vous pouvez ouvrir pour accéder à d'autres noeuds ou éléments. Si vous faites un clic simple sur
    un élément, son contenu sera inséré dans le document. Pour ouvrir/fermer un noeud, double-cliquez le.
  </paragraph>

  <paragraph title="Fichiers XInsert">
    Vous pouvez ajouter vos propres données dans le <b>XTree</b> en créant de nouveaux fichiers XInsert.
    Un fichier XInsert est un fichier textuel portant l'extension <b>.insert.xml</b> et placé dans
    le répertoire <b>&lt;home&gt;/.jext/xinsert</b>. Le répertoire &lt;home&gt; est /home/utilisateur
    sous système Un*x. Sous Windows, il s'agit de C:\Windows (si la machine ne contient pas plusieurs
    utilisateurs) ou C:\Windows\Profiles\Utilisateur. Les fichiers XInsert doivent contenir un ensemble
    de balises basées sur la définition de document (DTD) <b>xinsert.dtd</b> qui peut être trouvée dans le
    fichier <b>&lt;chemin de jext&gt;/lib/jext.jar</b>.
  </paragraph>
  <paragraph>
    Ecrire un fichier XInsert est relativement simple. Malgré tout, quelques règles doivent être
    impérativement respectées. Tout d'abord, il vous faut déclarer votre document comme un document XML
    en plaçant la ligne suivant au tout début:
    <code>&lt;?xml version="1.0" encoding="UTF-8"?&gt;</code>
    Ensuite, vous devez valider l'utilisation de la DTD:
    <code>&lt;!DOCTYPE xinsert SYSTEM "xinsert.dtd"&gt;</code>
    Enfin, créez la balise racine qui contiendra toutes les autres balises:
    <code>&lt;xinsert&gt;&lt;/xinsert&gt;</code>
  </paragraph>
  <paragraph>
    Tout est maintenant prêt pour que vous puissiez créer vos propres noeuds et éléments. A l'intérieur
    de la balise <b>&lt;xinsert&gt;</b> vous pouvez placer autant de balises <b>&lt;menu&gt;</b> que vous
    le désirez. Voici la structure de cette balise:
    <code>&lt;menu name="MENU_NAME" [modes="MODES"]&gt;&lt;/menu&gt;</code>
    La partie entre crochets [] est optionelle. Si vous spécifiez cet attribut ainsi:
    <b>modes="java cc"</b> le noeud n'apparaîtra que lorsque le mode de coloration Java ou C++ sera sélectionné.
    Seuls les noeuds "parents" seront affectés par ceci (c'est à dire les noeuds n'étant pas contenu dans
    un autre noeud).
  </paragraph>
  <paragraph>
    Un élément menu peut contenir autant de balises menu (pour créer des sous-noeuds)
    et de balises <b>&lt;item&gt;</b> que vous le souhaitez. Voici la structure d'une balise item:
    <code>&lt;item name="ITEM NAME" [type="plain|script|mixed"]&gt;ITEM CONTENTS&lt;/item&gt;</code>
    La partie entre crochets [] est optionnelle. L'attribut <b>type</b> peut prendre trois valeurs:
    <i>plain</i> agit comme si vous n'aviez pas écrit l'attribut, <i>script</i> définit le contenu de
    l'élément en tant que script à exécuter, et <i>mixed</i> permet de créer du texte contenant des scripts
    qui seront exécutés. <b>ITEM_CONTENTS</b> correspond au texte qui sera inséré ou exécuté dans le document
    lors d'un clic. Exemple d'un élément de type mixed:
    <code>&lt;item name="Elément Mixed" type="mixed"&gt;Salut %"Votre nom:" input% !&lt;/item&gt;</code>
    Lors d'un clic sur cet élément, l'utilisateur se verra demandé son nom et le message "Salut nom_entré !"
    sera inséré dans le texte. Voici un second exemple:
    <code>&lt;item name="Elément Mixed 2" type="mixed"&gt;La date du jour est: %date%&gt;</code>
    Cet élément, affiche simplement un message donnant la date.
  </paragraph>
  <paragraph>
    Vous pourrez trouver de nombreux exemples de construction de tels fichiers en regardant les fichiers
    *.insert.xml dans le fichier jext.jar de Jext ou bien dans l'archive contenant le code source du logiciel.
  </paragraph>
</xtiny-doc-page>

<!-- End of Jext documentation -->

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/xml-en/jext-editor.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xtiny-doc-page SYSTEM "../dtd/xtiny-doc-page.dtd" >

<!--
  -
  - Jext documentation source document
  - Based on xtiny-doc DTD
  -
  - DTD:xtiny-doc and XSL:xtiny-doc
  - are (C)1999 Romain Guy
  -
  - Last updated: 12/02/2001 - 22:15:37
  -
  -->

<xtiny-doc-page author="Romain Guy"
           update="12/02/2001"
           name="Jext : Editor"
           title="Editor"
           prev="jext-menus-jext.html"
           next="jext-search.html">

  <paragraph title="Overview">
    The Jext text area is familiar to anyone who is used to a modern text editor.
    To add text, simply click in the area and enter your desired text. Beyond this basic usage,
    the Jext text area has many other useful features which are described below.
  </paragraph>

  <paragraph title="Popup menu">
    A right click in the text area will open the text area's popup menu. The popup menu
    contains many items from the Edit menu as well as others such as Search and Tools.
    Using the popup menu can increase your productivity.
  </paragraph>

  <paragraph title="Key shortcuts">
    As a matter of fact, Jext's text area accepts several key shortcuts which will greatly
    help you in writing your text. Shortcuts make selecting and moving text easier. Here is
    a list of them:
  </paragraph>

  <menu>
    <item name="TAB">
      Indents the selected block of code.
    </item>
    <item name="S+TAB">
      De-indents selected block.
    </item>
    <item name="CA+UP">
      Scrolls up the text view by one line without changing the caret position relative
      to the text.
    </item>
    <item name="CA+DOWN">
      Scrolls down the text view by one line without changing the caret position relative
      to the text.
    </item>
    <item name="CA+PAGE_UP">
      Scrolls up the text view by one page without changing the caret position relative
      to the text.
    </item>
    <item name="CA+PAGE_DOWN">
      Scrolls down the text view by one page without changing the caret position relative
      to the text.
    </item>
    <item name="C+UP">
      Goes to the previous line, if one exists, starting at the first non-whitespace character.
    </item>
    <item name="C+DOWN">
      Goes to the next line, if one exists, starting at the first non-whitespace character.
    </item>
    <item name="C+LEFT">
      Jumps to the beginning of previous word. A word can be delimited by whitespace as well 
      as by other symbols like braces, dots, etc...
    </item>
    <item name="C+RIGHT">
      Jumps to beginning of the next word.
    </item>
    <item name="CS+LEFT|RIGHT">
      Selects up to beginning/end of a word.
    </item>
    <item name="CA+LEFT|RIGHT">
      Acts as C+LEFT|RIGHT but this action is case sensitive. If a word contains capitalized letters,
      this shortcut will use them as separators. Very useful in programming.
    </item>
    <item name="CAS+LEFT|RIGHT">
      Case sensitive word selection.
    </item>
    <item name="C+DELETE">
      Deletes next word.
    </item>
    <item name="C+BACK_SPACE">
      Deletes previous word.
    </item>
    <item name="CA+BACK_SPACE">
      Deletes previous word, case sensitive.
    </item>
    <item name="CAS+DELETE">
      Deletes next word, case sensitive.
    </item>
    <item name="INSERT">
      Switches between insert and replace modes. Insert mode is the default. While in
      replace mode, each character typed will overwrite the one under or above the caret 
      (depending on which caret, block or line respectively, you choose).
    </item>
    <item name="HOME">
      Goes to beginning of the current line. If Smart HOME/END option is activated, pressing
      this key twice will place your caret at the top of the visible text and pressing it three
      times will place your caret at the beginning of the document.
    </item>
    <item name="C+HOME">
      Jumps to the beginning of the document.
    </item>
    <item name="END">
      Jumps to the end of the current line. If Smart HOME/END option is activated, pressing
      this key twice will place your caret to the bottom of the visible text and pressing it three
      times will place your caret at the end of the document.
    </item>
    <item name="C+END">
      Jumps to the end of the document.
    </item>
    <item name="C+TAB">
      Browses through opened document to the right.
    </item>
    <item name="CS+TAB">
      Browses through opened document to the left.
    </item>
    <item name="S+[LEFT | RIGHT | UP | DOWN]">
      Selects a part of the text. Each <b>S+LEFT</b> or <b>S+RIGHT</b> press will select the 
      next character whereas <b>S+DOWN</b> and <b>S+UP</b> will include part of an adjacent
      line. This can be combined with the <b>C</b> key. For instance, <b>SC+LEFT</b> will select
      the previous word.
    </item>
    <item name="C+[MOUSE LEFT BUTTON]">
      Move the mouse while holding those keys down to make a rectangular selection.
    </item>
    <item name="[Dragging a selection]">
      Moves the selected text from one place to another.
    </item>
    <item name="C+[Dragging a selection]">
      Copies the selected text from one place to another.
    </item>
  </menu>

  <paragraph title="Hyper Typer">
    The standard Jext distribution comes with a plugin called HyperTyper. This plugin helps you
    to save lots of time and typing. It is very easy to use: you define an abbreviation which
    stands for a string of text, type the shorthand sequence (the abbreviation), press
    <b>ESCAPE</b> (this expansion key can be changed in plugins options) and automagically,
    HyperTyper expands the shorthand sequence into the text you've defined. The defaults 
    are mainly designed for Java programmers, but because HyperTyper is so flexible, it's suitable to
    whatever line of work you're in. To add/remove/edit shorthands, click on Plugins-HyperTyper-Manager
    Window. Transient abbreviations are lost when Jext is closed whereas persistent ones will
    be available in the next session.
  </paragraph>
  <paragraph>
    To add a new sequence, simply select some text to be stored as expanded text
    and press <b>C+F5</b> (or click on Plugins-HyperTyper-Create Sequence). A new window appears
    which allows you to modify the selected text, to choose the type of the abbreviation 
    (transient or persistent), and to give it an abbreviation.
  </paragraph>

  <paragraph title="Gutter">
    Along the left of the text area, you can see a thin grey line which indicates the gutter is present.
    Double-clicking it or clicking then dragging it will show it. The gutter offers 
    line numbering of the text area and highlights line numbers every 5 lines. The gutter can
    be customized in the options menu.
  </paragraph>
</xtiny-doc-page>

<!-- End of Jext documentation -->

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/xml-en/jext-templates.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xtiny-doc-page SYSTEM "../dtd/xtiny-doc-page.dtd" >

<!--
  -
  - Jext documentation source document
  - Based on xtiny-doc DTD
  -
  - DTD:xtiny-doc and XSL:xtiny-doc
  - are (C)1999 Romain Guy
  -
  - Last updated: 12/02/2001 - 22:59:15
  -
  -->

<xtiny-doc-page author="Romain Guy"
           update="12/02/2000"
           name="Jext : Templates"
           title="Templates"
           prev="jext-options.html"
           next="jext-scripts.html">

  <paragraph title="Overview">
    The templates are available from Jext file menu and allow to quickly create a new file.
  </paragraph>

  <paragraph title="Using the templates">
    The templates menu is built from the directory <b>jext_directory/bin/templates</b>. This directory can be
    set in the options dialog. When clicking on a template, Jext will prompt you for each variable 
    specified in the chosen template. At the end, Jext will ask you to save the file. Once
    saved, this file will be automatically opened for editing.
  </paragraph>

  <paragraph title="Creating a new template">
    To create a new template, create a new file and place it in the templates directory. You define variables
    using the following sequence: <b>__VARIABLE__</b> (2 underscores on each side). If you want
    to enter the two underscores (<b>__</b>) without having it interpreted by Jext as a variable,
    enter <b>____</b> (4 underscores).
  </paragraph>
    
</xtiny-doc-page>

<!-- End of Jext documentation -->

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/xml-fr/jext-menus-edit.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xtiny-doc-page SYSTEM "../dtd/xtiny-doc-page.dtd" >

<!--
  -
  - Jext documentation source document
  - Based on xtiny-doc DTD
  -
  - DTD:xtiny-doc and XSL:xtiny-doc
  - are (C)1999 Romain Guy
  -
  - Last updated: 09/30/2001 - 15:52:03
  -
  -->

<xtiny-doc-page author="Romain Guy"
           update="09/30/2001"
           name="Menu Edition"
           title="Jext : Menu Edition"
           prev="jext-menus-file.html"
           next="jext-menus-search.html">

  <paragraph title="Présentation">
   Le menu <b>Edition</b> contient toutes les fonctions relatives à l'édition du texte même. Il contient
   des fonctions classiques d'édition (telles que copier, coller...) aussi bien que des fonctions plus puissantes
   (par exemple, complétion des mots).
  </paragraph>

  <menu title="Contenu">
    <item name="Annuler">
      Annule la dernière action d'édition. Par exemple, si vous collez le texte "N'Cha !", l'appui sur
      <b>Annuler</b> enlèvera ledit texte.
    </item>
    <item name="Refaire">
      Refait l'action précédemment annulée par Jext.
    </item>
    <item name="Copier">
      Copie le texte sélectionné dans le presse-papier.
    </item>
    <item name="Couper">
      Coupe (c'est à dire copie puis supprime) le texte sélectionné dans le presse-papier.
    </item>
    <item name="Coller">
      Insère le contenu du presse-papier dans votre texte au niveau du curseur.
    </item>
    <item name="Coller Filtré">
      Insère le contenu du presse-papier dans votre texte après avoir effectué sur ce contenu une opération
      de type "rechercher et remplacer tout". Les motifs et les options utilisées pour cette opération sont
      ceux définis dans la boîte de dialogue Remplacer.
    </item>
    <item name="Coller/Insertion">
      Insère le contenu du presse-papier dans votre texte au niveau du curseur. Cette fonction ne change pas
      la position du curseur.
    </item>
    <item name="Sélectionner Tout">
      Sélectionne l'intégralité de votre document.
    </item>
    <submenu title="Ancres">
      <item name="Poser Ancre">
        Pose une ancre sous votre curseur. Notez que cette ancre est relative au texte et non à la position.
        Par exemple, si vous posez une ancre devant le mot "Claire" à la ligne 11, puis que vous effacez
        quelques lignes, l'ancre sera toujours placée devant le mot "Claire".
      </item>
      <item name="Aller Ancre">
        Déplace votre curseur sur l'ancre. Si vous n'avez pas déposé l'ancre, rien ne se passera.
      </item>
      <item name="Echanger Ancre/Curseur">
        Place le curseur sur l'ancre et déplace l'ancre sur l'ancienne position du curseur. Cette action
        est une combinaison de "Poser Ancre" et de "Aller Ancre".
      </item>
      <item name="Sélectionner Vers Ancre">
        Sélectionne le texte depuis votre curseur jusqu'à l'ancre, positionnant ainsi votre curseur sur l'ancre.
      </item>
      <item name="Sélectionner Depuis Ancre">
        Sélectionne le texte depuis l'ancre jusqu'à votre curseur, laissant ainsi votre curseur à sa position
        actuelle.
      </item>
    </submenu>
    <submenu title="Code Source">
      <item name="Indentation">
        Indente le bloc de code sélectionné d'une tabulation vers la droite. Si l'option activant la conversion
        des tabulations en espaces est activée, l'indentation se fera à l'aide de caractères d'espacement simple.
      </item>
      <item name="Désindentation">
        Agit de la même manière que la fonction "Indentation" mais vers la gauche.
      </item>
      <item name="Crochet Correspondant">
        Si le caractère sous le curseur est une parenthèse, une accolade ou un crochet, cette fonction déplacera
        le curseur jusqu'au caractère de correspondant.
      </item>
      <item name="Commentaire">
        Enferme le texte sélectionné dans un commentaire. Les caractères de commentaire dépendent du langage
        sélectionné dans le mode de coloration. Ainsi, en Java, C et C++, cette fonction ajoute <b>/*</b> au début
        du texte et <b>*/</b> à la fin ainsi que <b>*</b> au début de chaque ligne.
      </item>
      <item name="Bloc De Commentaire">
        Enferme le texte sélectionné dans un commentaire. Les caractères de commentaire dépendent du langage
        sélectionné dans le mode de coloration. Ainsi, en Java, C et C++, cette fonction ajoute <b>/*</b> au début
        du texte et <b>*/</b> à la fin.
      </item>
      <item name="Commenter Bloc">
        Ajoute un commentaire simple au début de chaque ligne sélectionnée. En Java, C ou C++, chaque ligne
        commencera alors par <b>//</b>.
      </item>
      <item name="Décommenter Bloc">
        Retire les commentaires créés par l'action "Commenter Bloc".
      </item>
    </submenu>
    <submenu title="Texte">
      <item name="Tabs En Espaces">
        Convertit tous les caractères de tabulation du texte en leur équivalent d'espaces simples.
      </item>
      <item name="Espaces En Tabs">
        Convertit si possible toutes les séquences d'espaces en caractère de tabulation.
      </item>
      <item name="Commencer Lignes Par">
        Affiche une boîte de dialogue demandant un texte. Ensuite, ce texte sera ajouté au début de chacune
        des lignes sélectionnées.
      </item>
      <item name="Finir Lignes Par">
        Agit de la même manière que la fonction précédente mais ajoute le texte à la fin des lignes.
      </item>
      <item name="Majuscules">
        Convertit en majuscule toute minuscule contenue dans le texte sélectionné.
      </item>
      <item name="Minuscules">
        Convertit toute majuscule contenur dans le texte sélectionné en minuscule.
      </item>
      <item name="Trier Lignes">
        Trie les lignes sélectionnées par ordre alphabétique.
      </item>
      <item name="Tri Inverse Des Lignes">
        Trie les lignes sélectionnées par ordre alphabétique inverse.
      </item>
      <item name="Joinde Lignes">
        Joint la ligne en cours d'édition avec la ligne suivante.
      </item>
      <item name="Joinde Toutes Les Lignes">
        Joint toutes les lignes de votre document. Le document final est plus petit, ne contient qu'une ligne
        mais est difficile à modifier.
      </item>
      <item name="Supprimer Espaces Finaux">
        Supprime tous les espaces et toutes les tabulations se trouvant en fin de ligne. Cette fonction
        permet de réduire la taille d'un document.
      </item>
      <item name="Transposer Lignes">
        Remplace la ligne en cours d'édition par la ligne précédente et vice-versa.
      </item>
      <item name="Compléter Mot">
        Tente de compléter le mot. Par exemple, si vous avez déjà tapé "anticonstitutionnellement", il peut
        être astreignant de le retaper chaque fois que vous en aurez l'usage dans votre texte. Il vous suffit
        en fait de taper le début du mot (par exemple: "antic") et de lancer cette fonction (raccourci par
        défaut: <b>C+b</b>). Jext complètera alors automatiquement "antic" ! Si Jext trouve plusieurs
        mots susceptibles d'être celui que vous souhaitez, une fenêtre apparaît pour vous laisser le choix.
      </item>
      <item name="Compter Mots">
        Cette action résume les informations concernant votre texte: le nombre de lignes, de caractères,
        de mots et, pour les programmeurs, le nombre de lignes de code réelles (en excluant les lignes
        vides et les lignes commentées).
      </item>
    </submenu>
    <submenu name="Fichier">
      <item name="Insérer Extension">
        Insère l'extension de fichier du document.
      </item>
      <item name="Insérer Nom Complet">
        Insère le nom du fichier édité avec extension.
      </item>
      <item name="Insérer Nom">
        Insère le nom du fichier édité sans extension.
      </item>
      <item name="Insérer Chemin Complet">
        Insère le chemin absolu du fichier édité (avec nom du fichier).
      </item>
      <item name="Insérer Chemin">
        Insère le chemin absolu du fichier édité (sans nom du fichier).
      </item>
    </submenu>
    <item name="Aller Ligne">
      Cette fonction permet de déplacer le curseur à une ligne donnée en entrant simplement son numéro.
    </item>
    <item name="Supprimer Ligne">
      Supprime la ligne.
    </item>
    <item name="Date/Heure">
      Insère la date et l'heure dans votre document.
    </item>
    <submenu title="One Click!">
      <item name="Terminer One Click!">
        Lorsque vous souhaitez mettre fin à une séquence <b>One Click!</b>, vous pouvez soit cliquez sur cet
        élément, soit cliquer sur n'importe quel autre élément. Mais celui-ci ne lance aucune opération.
      </item>
      <item name="[une action]">
        Les éléments <b>One Click!</b> activent le système du même nom. Vous pouvez vérifier si le système
        est actif ou non en regardant en bas à droite de la zone de texte. La mention "one click!" apparaît
        si la fonction est active. Une fois le système activé, chaque clic dans la zone de texte lancera
        l'opération d'édition. Par exemple, si vous avez cliqué sur <b>Coller</b>, chaque clic dans la zone
        de texte collera le contenu du presse-papier.
      </item>
    </submenu>
    <item name="Options">
      Affiche la fenêtre des options de Jext. Reportez-vous à la section <a href="jext-options.html">Options</a>
      pour de plus amples informations.
    </item>
  </menu>
</xtiny-doc-page>

<!-- End of Jext documentation -->
