=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/dtd/xtiny-doc-page.dtd
<!ELEMENT xtiny-doc-page (paragraph+ | break | menu)* >
  <!ATTLIST xtiny-doc-page author CDATA #REQUIRED
                           update CDATA #REQUIRED
                           title CDATA #REQUIRED
                           name CDATA #REQUIRED
                           prev CDATA #IMPLIED
                           next CDATA #IMPLIED >

  <!-- Equivalent to CODE tag in HTML: code -->
  <!ELEMENT code (#PCDATA) >

  <!-- Equivalent to B tag in HTML: bold -->
  <!ELEMENT b (#PCDATA) >

  <!-- Equivalent to I tag in HTML: italic -->
  <!ELEMENT i (#PCDATA) >

  <!-- Equivalent to A tag in HTML: anchor -->
  <!ELEMENT a (#PCDATA) >
    <!ATTLIST a href CDATA #REQUIRED >

  <!ELEMENT menu (submenu | item)* >
    <!ATTLIST menu title CDATA #IMPLIED >

  <!ELEMENT submenu (item*) >
    <!ATTLIST submenu title CDATA #REQUIRED >

  <!ELEMENT item (#PCDATA) >
    <!ATTLIST item name CDATA #REQUIRED >

  <!-- A paragraph which can be titled -->
  <!ELEMENT paragraph (#PCDATA | b | i | a | code)* >
    <!ATTLIST paragraph title CDATA #IMPLIED >

  <!-- An horizontal rule -->
  <!ELEMENT break EMPTY >

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/xml-en/jext-menus-edit.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xtiny-doc-page SYSTEM "../dtd/xtiny-doc-page.dtd" >

<!--
  -
  - Jext documentation source document
  - Based on xtiny-doc DTD
  -
  - DTD:xtiny-doc and XSL:xtiny-doc
  - are (C)1999 Romain Guy
  -
  - Last updated: 12/02/2001 - 22:15:51
  -
  -->

<xtiny-doc-page author="Romain Guy"
           update="12/02/2001"
           name="Edit Menu"
           title="Jext : Edit Menu"
           prev="jext-menus-file.html"
           next="jext-menus-search.html">

  <paragraph title="Overview">
    The <b>Edit</b> menu contains features specific to editing text, including
    basic text editing options (cut, copy, paste...) as well as advanced ones (expand
    abbreviation...).
  </paragraph>

  <menu title="Contents">
    <item name="Undo">
     Undoes the last editing action. For example, if you paste in the string "Hello World!", 
     <b>Undo</b> will remove it.
    </item>
    <item name="Redo">
      Redoes last <b>Undo</b> operation.
    </item>
    <item name="Copy">
      Copies the selected text from the text area to the system clipboard.
    </item>
    <item name="Cut">
      Cuts (i.e. copies then removes) the selected text to the system clipboard.
    </item>
    <item name="Paste">
      Inserts the contents of the system clipboard into the text area at the caret position.
    </item>
    <item name="Filtered Paste">
      Inserts the contents of the system clipboard into the text area after having performed a "search and
      replace all" operation on it. The patterns and options used for this purpose are the ones set
      in the Search And Replace dialog.
    </item>
    <item name="Insert Paste">
      Inserts the contents of system clipboard into the text area at the caret position. This
      function does not move caret after insertion.
    </item>
    <item name="Select All">
      Selects all the text.
    </item>
    <submenu title="Anchor">
      <item name="Set Anchor">
        Drops the anchor at the caret position. Note that this anchor is relative to the text
        and NOT an offset in the file. For instance, if you drop anchor in front of the word "Duke"
        at line 11, then delete the ten first lines, the anchor will still be in front of
        the word "Duke."
      </item>
      <item name="Goto Anchor">
        Places the caret at the anchor position. If the anchor hasn't been dropped (or set) yet, nothing
        happens. Read the explanation of the <b>Set Anchor</b> menu item carefully to understand
        why an anchor is so useful.
      </item>
      <item name="Exchange Caret/Anchor">
        Substitutes the caret with the anchor and vice versa. This means your caret is placed at the
        anchor position (as <b>Goto Anchor</b> does) and that the anchor is dropped at the caret's
        former position. In other words, they swap locations.
      </item>
      <item name="Select To Anchor">
        Selects text from the caret to the anchor, placing the caret at the anchor position.
      </item>
      <item name="Select From Anchor">
        Selects text from the anchor to the caret, leaving the caret in its current position.
      </item>
    </submenu>
    <submenu title="Source Code">
      <item name="Block Right Indent">
        Indents the selected block of text to the right. The amount of indent is controlled by
        the tab size option.
      </item>
      <item name="Block Left Indent">
        Does exactly the same as <b>Block Right Indent</b>, but to the left.
      </item>
      <item name="Jump To Matching Bracket">
        If the character under the caret is a brace, a bracket or a parenthesis, this function will move the
        caret to the matching one.
      </item>
      <item name="Box Comment">
        Encloses selected text in a wing comment adding a special character in front of
        each line. Comment characters depend on current selected syntax colorizing mode. For instance, Java,
        C and C++ modes will add <b>/*</b> at the beginning of the block and <b>*/</b> at its end and each
        line will begin with <b>*</b>.
      </item>
      <item name="Wing Comment">
        Encloses selected text in a wing comment. Comment characters depends on current selected
        syntax colorizing mode. For instance, Java, C and C++ modes will add <b>/*</b> at the
        beginning of the block and <b>*/</b> at its end.
      </item>
      <item name="Comment Block">
        Adds a single comment at the beginning of each selected line. In Java, C or C++ syntax
        colorizing mode, each line will begin with <b>//</b>. Comment characters depends on
        current selected syntax colorizing mode.
      </item>
      <item name="UnComment Block">
        Removes comment characters within the selected block of code.
      </item>
    </submenu>
    <submenu title="Text">
      <item name="Tabs To Spaces">
        Converts all tab characters in your text to the equivalent spaces.
      </item>
      <item name="Spaces To Tabs">
        If possible, converts spaces to tab characters. For example, if you set Tab Size
        to 8, each sequence of 8 spaces will be converted into a single tab character.
      </item>
      <item name="Begin Lines With">
        Displays an input dialog in which you have to enter some text. Jext then adds this
        text to the beginning of each selected line.
      </item>
      <item name="End Lines With">
        Displays an input dialog which prompts for text to be added to the end of each selected line.
      </item>
      <item name="To Upper Case">
        Turns each lower-case character of selected text to its upper-case equivalent.
      </item>
      <item name="To Lower Case">
        Turns each upper-case character of selected text to its lower-case equivalent.
      </item>
      <item name="Sort Lines">
        Sorts selected lines alphabetically using the first non-blank characters
        of each line.
      </item>
      <item name="Reverse Sort Lines">
        Sorts selected lines reverse alphabetically using the first non-blank characters
        of each line.
      </item>
      <item name="Join Lines">
        Joins the line on which the caret is placed with the next one. If the next line begins with more than one
        blank character, those characters are removed.
      </item>
      <item name="Join All Lines">
        Joins all lines contained in your text into a single line. This can greatly save space
        for Web pages (and in this way bandwidth and download times). However, it makes future 
        edits more difficult.
      </item>
      <item name="Remove End Spaces">
        Removes all white space characters from the end of each line of
        text. As with <b>Join All Lines</b>, using this feature can save some loading time
        for Web pages.
      </item>
      <item name="Transpose Lines">
        This function swaps the line of text located on the caret line with the
        previous line of text.
      </item>
      <item name="Complete Word">
        Tries to expand the current word. For instance, if you have already typed "thisIsAnotherVariable",
        it can be exhausting to retype it each time you need to use it, right? Instead, just begin
        to type it (type: "thisIsA", for example) and fire <b>Expand Abbreviation</b> action [Ctrl-b].
        Jext will auto-complete "thisIsA" to write the complete word for you ! If several words in the text
        match the abbreviation, a window pops up and let you choose the word you need.
      </item>
      <item name="Word Count">
        Displays summary information about the current document: the number
        of lines, characters, words and, for programmers only, real-code lines (this excludes blank
        and commented lines).
      </item>
    </submenu>
    <submenu title="File">
      <item name="Insert Extension">
        Inserts the current document's extension name at the caret.
      </item>
      <item name="Insert Full Name">
        Inserts the current document's full name (with extension) at the caret.
      </item>
      <item name="Insert Name">
        Inserts the current document's name (with no extension) at the caret.
      </item>
      <item name="Insert Full Path">
        Inserts the current document's full path (absolute path and file name) at the caret.
      </item>
      <item name="Insert Path">
        Inserts the current document's absolute path (without the full file name) at the caret.
      </item>
    </submenu>
    <item name="Goto Line">
      Displays an input dialog box which prompts for a line number. When <b>Ok</b> is clicked,
      Jext places the caret at the beginning of the specified line, if it exists.
    </item>
    <item name="Delete Line">
      Deletes the line on which the caret is placed.
    </item>
    <item name="Date/Time">
      Inserts the current date and time in your text at the caret.
    </item>
    <submenu title="One Click!">
      <item name="End One Click!">
        When you want to disable the <b>One Click!</b> feature, you can either use this item, either click
        any other menu item.
      </item>
      <item name="[an action]">
        <b>One Click!</b> menu items activate the <b>One Click!</b> system. You can tell if the feature is activated
        by the "one click!" message displayed in the bottom right corner of the text area. Once 
        activated, each click within the text area will perform an action. For instance, after
        having clicked <b>Paste</b>, each click will paste clipboard contents.
      </item>
    </submenu>
    <item name="Options">
      Displays the Jext options dialog. See the <a href="jext-options.html">Options</a> section
      for more information.
    </item>
  </menu>
</xtiny-doc-page>

<!-- End of Jext documentation -->

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/xml-fr/jext-search.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xtiny-doc-page SYSTEM "../dtd/xtiny-doc-page.dtd" >

<!--
  -
  - Jext documentation source document
  - Based on xtiny-doc DTD
  -
  - DTD:xtiny-doc and XSL:xtiny-doc
  - are (C)1999 Romain Guy
  -
  - Last updated: 09/30/2001 - 11:27:06
  -
  -->

<xtiny-doc-page author="Romain Guy"
           update="09/30/2001"
           name="Jext : Recherche"
           title="Rechercher Et Remplacer"
           prev="jext-editor.html"
           next="jext-console.html">

  <paragraph title="Présentation">
    Le menu <b>Recherche</b> de la barre de menus propose plusieurs fonctions de recherche et de remplacemen
    au sein de vos documents. Nous allons détailler trois d'entre elles, celles ouvrant de nouvelles
    fenêtres.
  </paragraph>

  <paragraph title="Rechercher">
    L'élément <b>Rechercher</b> de Jext affiche une boîte de recherche à l'écran. Dans cette fenêtre,
    trois composants sont grisés: ceux-ci ne sont activés que lorsque vous tentez une opération de remplacement.
    Pour lancer une recherche, entrez simplement un motif de recherche dans le champ de texte puis appuyez sur
    le bouton <b>Rechercher</b>. Notez que le champ de texte conserve en mémoire les 25 derniers motifs utilisés.
  </paragraph>
  <paragraph>
    Le bouton <b>Annuler</b> quant à lui sert à fermer la fenêtre. Enfin, il y a quatre cases à cocher
    en bas de la fenêtre. Ces cases permettent de modifier le comportement des recherches:
    <menu>
      <item name="Ignorer Casse">
        Si cette case est cochée, la casse des lettres sera ignorée. Par exemple, l'utilisation du motif
        <b>java</b> avec la case cochée définira le texte <b>JAVA</b> comme un résultat de la recherche.
      </item>
      <item name="Sauver valeurs">
        Lorsque vous quittez la fenêtre et que cette option est cochée, Jext sauvegardera votre configuration.
      </item>
      <item name="Tous Fichiers">
        Exécute l'opération dans tous les fichiers ouverts.
      </item>
      <item name="Expressions Régulières">
        Par défaut, Jext effectue une recherche standard. Si vous cochez cette case, Jext utilisera la syntaxe
        Perl5 pour sa recherche. Cela permet d'effectuer des recherches plus précises.
      </item>
    </menu>
  </paragraph>

  <paragraph title="Remplacer">
    Un clic sur l'élément <b>Remplacer</b> ouvre la même fenêtre que précédemment. Cependant, celle-ci
    affiche maintenant des composants activés dans sa partie basse. L'utilisation de cette fenêtre se
    fait de la même manière que celle destinée à la recherche. Sachez seulementque le bouton <b>Remplacer</b>
    remplacera l'occurence courante du motif de recherche et lancera la recherche pour l'occurence suivante.
    Enfin, le bouton <b>Remplacer Tout</b> lancera l'opération de remplacement dans tous les fichiers ouverts
    dans l'éditeur. A l'instar de la commande <b>Rechercher</b>, le champ de texte conserve en mémoire les
    25 derniers motifs de remplacement utilisés.
  </paragraph>
  <paragraph>
    Vous pouvez également utiliser la fonction de Script. Cette fonction permet de remplacer chaque résultat de
    la recherche provoqué par une expression régulière par le résultat de l'évaluation d'un script Python.
    Si vous recherchez par exemple l'expression &lt;([^&lt;&gt;]*)&gt;, Jext recherchera chaque tag HTML défini dans le texte.
    Si vous employez l'option Script avec la valeur : "&lt;" + _m[0].upper() + "&gt;" et que vous pressez <b>Remplacer Tout</b>
    chaque tag HTML sera mis en majuscules. Sachez juste que l'objet _m représente un tableau contenant les valeurs
    de chacun des groupes (créés avec des parenthèses) de l'expressions régulière.
  </paragraph>

  <paragraph title="Rechercher Tout">
    Bien que la fenêtre de la fonction <b>Rechercher Tout</b> soit sensiblement différente de la fenêtre
    de recherche/remplacement, les options proposées restent les mêmes. Lorsque vous lancez une recherche
    depuis cette boîte de dialogue, Jext listera toutes les occurences du motif de recherche dans une liste.
    Un clic sur un élément de la liste permettra de placer le curseur à l'endroit de l'occurence. La case
    "Souligner" permet de souligner toutes les occurences en bleu au sein du texte même.
  </paragraph>
</xtiny-doc-page>

<!-- End of Jext documentation -->

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/xml-fr/jext-templates.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xtiny-doc-page SYSTEM "../dtd/xtiny-doc-page.dtd" >

<!--
  -
  - Jext documentation source document
  - Based on xtiny-doc DTD
  -
  - DTD:xtiny-doc and XSL:xtiny-doc
  - are (C)1999 Romain Guy
  -
  - Last updated: 09/30/2001 - 22:25:59
  -
  -->

<xtiny-doc-page author="Romain Guy"
           update="09/30/2001"
           name="Jext : Modèles"
           title="Modèles"
           prev="jext-options.html"
           next="jext-scripts.html">

  <paragraph title="Présentation">
    Les modèles, disponibles dans le menu Fichier de Jext permettent de créer rapidement un nouveau fichier.
  </paragraph>

  <paragraph title="Utilisation des modèles">
    Le menu modèles est basé, par défaut, sur le répertoire <b>rép_de_jext/bin/templates</b>. Ce répertoire
    peut être changé dans les options générales. Lorsque vous cliquez sur un modèle donné, Jext vous posera
    plusieurs questions pour remplacer les variables par la valeur que vous leur donnerez. A la fin, Jext
    vous demandera de sauvegarder le fichier. Ensuite, le fichier sera automatiquement ouvert dans l'éditeur.
  </paragraph>

  <paragraph title="Créer un nouveau modèle">
    Pour créer un nouveau modèle, il vous suffit de créer un nouveau fichier et de la placer dans le répertoire
    des modèles. Vous pouvez créer une variable en entrant une séquence du type: <b>__VARIABLE__</b> (2 soulignés
    de chaque côté). Si vous souhaitez entrer le texte <b>__</b> sans que Jext l'interprète comme une variable,
    vous devrez taper <b>____</b> (4 soulignés).
  </paragraph>
    
</xtiny-doc-page>

<!-- End of Jext documentation -->

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/xml-en/jext-menus-search.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xtiny-doc-page SYSTEM "../dtd/xtiny-doc-page.dtd" >

<!--
  -
  - Jext documentation source document
  - Based on xtiny-doc DTD
  -
  - DTD:xtiny-doc and XSL:xtiny-doc
  - are (C)1999 Romain Guy
  -
  - Last updated: 12/02/2001 - 22:16:51
  -
  -->

<xtiny-doc-page author="Romain Guy"
           update="12/02/2001"
           name="Search Menu"
           title="Jext : Search Menu"
           prev="jext-menus-edit.html"
           next="jext-menus-tools.html">

  <paragraph title="Overview">
    The <b>Search</b> menu provides access to the search and replace features. Refer to the
    <a href="jext-search.html">Search</a> section for more information.
  </paragraph>

  <menu title="Contents">
    <item name="Find">
      Displays the Jext find dialog box. This dialog box can be used to enter a search pattern,
      set search options and start a search. Some components are grayed out (disabled) because they
      are meaningful to the <b>Replace</b> feature only.
    </item>
    <item name="Replace">
      Displays the same dialog as the <b>Find</b> option, but enables components which were
      disabled in <b>Find</b> feature.
    </item>
    <item name="Find All">
      Displays the Find All dialog which provides same options as <b>Find</b> feature but
      displays <b>all matches</b> in a list.
    </item>
    <item name="Find Next">
      Searches for the next occurence of the previous pattern used for a search. The previous pattern
      persists from one Jext session to the next.
    </item>
    <item name="Replace Next">
      Replaces the next occurence of previous search pattern with the previous replacement pattern.
    </item>
    <item name="Replace Selection">
      Replaces the current selection in the text area with the previous replacement pattern.
    </item>
  </menu>
</xtiny-doc-page>

<!-- End of Jext documentation -->

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/xml-en/jext-console.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xtiny-doc-page SYSTEM "../dtd/xtiny-doc-page.dtd" >

<!--
  -
  - Jext documentation source document
  - Based on xtiny-doc DTD
  -
  - DTD:xtiny-doc and XSL:xtiny-doc
  - are (C)1999 Romain Guy
  -
  - Last updated: 12/02/2001 - 22:15:26
  -
  -->

<xtiny-doc-page author="Romain Guy"
           update="12/02/2001"
           name="Jext : Console"
           title="Console"
           prev="jext-search.html"
           next="jext-xinsert.html">

  <paragraph title="Overview">
    The Jext console behaves exactly like any system console (or terminal). Thus, it can be used
    to browse disks, launch applications, etc...
  </paragraph>

  <paragraph title="Using the console">
    First, the console is by default hidden. You have to go into the options menu and
    activate the check box named "Show top tabbed pane".
  </paragraph>
  <paragraph>
    To use the console, simply click in it and type in your command, followed by <b>ENTER</b>
    to execute it. The Jext console provides many internal commands and variables (which generaly
    change according to the current selected document) as well as special keys.
  </paragraph>

  <paragraph title="Console prompt">
    Jext lets the user customize the prompt. The Default prompt is in of the form
    <b>user_name@absolute_path &gt;</b>. In the options, you can change this prompt. Jext provides,
    in addition to this prompt, three defaults: Linux (<b>user@host%</b>), Solaris
    (<b>host%</b>) and DOS (<b>path &gt;</b>). To customize your prompt, enter any text in the
    prompt text field in the options dialog. You can use one of the
    four following variables:
    <menu>
      <item name="$u">
        Includes the current user name in the prompt
      </item>
      <item name="$h">
        Includes the current host (computer) name in the prompt
      </item>
      <item name="$p">
        Includes the current working directory in the prompt
      </item>
      <item name="$$">
        Includes the character '$' in the prompt
      </item>
    </menu>
  </paragraph>

  <menu title="Internal commands">
    <item name="help">
      Displays a summary of the console commands and variables.
    </item>
    <item name="clear">
      Clears the console screen.
    </item>
    <item name="cd">
      Change directory. This command is a little bit different from your
      OS one as it accepts both / and \ path separators depending on your OS is. It also offers the
      use of the ~ character which stands for your home directory. Type <b>cd -help</b> to get
      more information about it.
    </item>
    <item name="exit">
      Exits Jext.
    </item>
    <item name="home">
      This command does a <b>cd &lt;jext home dir&gt;</b>.
    </item>
    <item name="ls">
      Un*x users already know this command. Windows users have to know that this function is
      the equivalent of their dir command. The ls command accepts many flags, type <b>ls -help</b>
      to get a description of each of them. Note that the command <b>dir</b> can be substituted
      with the <b>ls</b> command.
    </item>
    <item name="pwd">
      Print working directory. This is useful when you choose a non-DOS prompt type (Linux or
      Solaris type).
    </item>
    <item name="file:filename">
      Typing <b>file:filename</b> will open the name file. The path to this file can
      be relative (i.e file:../infos.txt) or absolute (i.e file:/etc/.bashrc). Note the path is
      built using the cd command.
    </item>
    <item name="http://URL">
      Opens a specified URL. Typing <b>http://www.jext.com/index.html</b> will
      for instance open Jext (virtual ;-) web site welcome page in Jext.
    </item>
    <item name="run:scriptname">
      Runs the script <b>scriptname</b>. To get more informations about Jext internal scripts,
      please see the <a href="jext-scripts.html">Scripts section</a>.
    </item>
    <item name="eval:scriptlet">
      Evaluates the script "scriptlet" as a Python script.
    </item>
  </menu>

  <paragraph title="Using variables">
    If you insert an internal variable in your command, the console will automatically expand it
    to its current value before executing the command line. If you've opened the file
    Hello.java in /home/Gfx/java/hello and you want to compile it, even if you
    use the cd command to go in the directory /home/Gfx/java/hello, you won't be able to compile
    the file. This is a Java limitation (usually done for portability concerns). But you can do it 
    using a variable. To compile the file, just type the command <b>javac $n/Hello.java</b>. Then, 
    to run the class Hello.class, type <b>java -classpath $n $e</b>. Variables can be very useful
    in many other cases, to go to a subdirectory for instance: <b>cd $n</b> or to delete the 
    file: <b>rm -f $f</b> (Un*x users only).
  </paragraph>

  <menu title="Internal variables">
    <item name="$j">
      Jext home directory.
    </item>
    <item name="$h">
      User's home directory (/home/user under Un*x, C:\Windows or C:\Windows\Profiles\User under
      Win32 environment).
    </item>
    <item name="$d">
      Current directory.
    </item>
    <item name="$f">
      Current (selected document) file (designed by its absolute path. Ex: C:\Gfx\Login.rtf).
    </item>
    <item name="$p">
      Current (selected document) file name.
    </item>
    <item name="$e">
      Current (selected document) file name with no extension.
    </item>
    <item name="$n">
      Current (selected document) file directory.
    </item>
    <item name="$s">
      Selected text in the editor.
    </item>
  </menu>

  <paragraph title="Console keys">
    The console also provides many keys to simplify and streamline its use. Here is a list of them:
  </paragraph>
  <menu>
    <item name="ESCAPE">
      Deletes the whole command line. If you typed a long command line and then changed your
      mind, simply hit <b>ESCAPE</b> to clear it and place your caret at the prompt.
    </item>
    <item name="LEFT">
      Moves caret to the left in the command line.
    </item>
    <item name="RIGHT">
      Moves caret to the right in the command line.
    </item>
    <item name="UP">
      Get previous typed command from the history (up to 25 commands in the history, the history
      is saved from one session to the next).
    </item>
    <item name="DOWN">
      Get next typed command from the history.
    </item>
    <item name="TAB">
      Completes the file name if a match is found in the current directory. For example, if you
      are in the a directory containing the file <b>jext-patch-2.8.0.3.zip</b>, you can type
      <b>jext-</b> and then press <b>TAB</b> for Jext to automatically complete the file name. If
      several files begin with your shorthand name, the longest common part among those files
      names will be displayed.
    </item>
    <item name="S+TAB">
      Completes a command if a match is found in the history. For example, if you already typed the
      command <b>ls -rind</b>, then if you type <b>ls</b> in the console, and press
      <b>TAB</b>, the console will expand your command line to <b>ls -rind</b>.
    </item>
    <item name="C+c">
      Copies selected text to the clipboard.
    </item>
    <item name="C+d">
      Kills (terminates) current process. If you ran an app which seems to have crashed or
      needs to be terminated, press <b>C+d</b>. C+d used instead of the standard C+c 
      because C+c is already used for copying selected text.
    </item>
  </menu>
</xtiny-doc-page>

<!-- End of Jext documentation -->
