=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/dtd/xtiny-doc-page.dtd
<!ELEMENT xtiny-doc-page (paragraph+ | break | menu)* >
  <!ATTLIST xtiny-doc-page author CDATA #REQUIRED
                           update CDATA #REQUIRED
                           title CDATA #REQUIRED
                           name CDATA #REQUIRED
                           prev CDATA #IMPLIED
                           next CDATA #IMPLIED >

  <!-- Equivalent to CODE tag in HTML: code -->
  <!ELEMENT code (#PCDATA) >

  <!-- Equivalent to B tag in HTML: bold -->
  <!ELEMENT b (#PCDATA) >

  <!-- Equivalent to I tag in HTML: italic -->
  <!ELEMENT i (#PCDATA) >

  <!-- Equivalent to A tag in HTML: anchor -->
  <!ELEMENT a (#PCDATA) >
    <!ATTLIST a href CDATA #REQUIRED >

  <!ELEMENT menu (submenu | item)* >
    <!ATTLIST menu title CDATA #IMPLIED >

  <!ELEMENT submenu (item*) >
    <!ATTLIST submenu title CDATA #REQUIRED >

  <!ELEMENT item (#PCDATA) >
    <!ATTLIST item name CDATA #REQUIRED >

  <!-- A paragraph which can be titled -->
  <!ELEMENT paragraph (#PCDATA | b | i | a | code)* >
    <!ATTLIST paragraph title CDATA #IMPLIED >

  <!-- An horizontal rule -->
  <!ELEMENT break EMPTY >

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/xml-en/jext-xinsert.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xtiny-doc-page SYSTEM "../dtd/xtiny-doc-page.dtd" >

<!--
  -
  - Jext documentation source document
  - Based on xtiny-doc DTD
  -
  - DTD:xtiny-doc and XSL:xtiny-doc
  - are (C)1999 Romain Guy
  -
  - Last updated: 12/02/2001 - 23:13:46
  -
  -->

<xtiny-doc-page author="Romain Guy"
           update="12/02/2001"
           name="Jext : XInsert"
           title="XInsert"
           prev="jext-console.html"
           next="jext-workspaces.html">

  <paragraph title="Overview">
    The default Jext interface displays a panel containing a tree on the left of the window. This
    panel is called the <b>XInsert Panel</b> and the tree <b>XTree</b>. The tree is dynamically
    built from a set of XML files shipped with Jext. Of course, you can add your own items in the
    XTree by creating your own XInsert definition files. Note that shown items depend on which
    syntax colorizing mode is chosen !
  </paragraph>
  <paragraph>
    The XInsert panel is an easy way to add pre-defined text in your documents. For instance,
    the Licenses node is able to insert the GNU/GPL license in your document. The XTree can also
    hold scripts which can act as macros. This page is dedicated to the use of the XInsert panel
    and the writing of the XInsert files.
  </paragraph>

  <paragraph title="XInsert Panel">
    The <b>XInsert Panel</b> layout is very simple. On the top of the panel, there are two
    buttons: <b>Collapse</b> and <b>Expand</b>. The first one will collapse all the XTree nodes
    whereas the second one will expand all the nodes.
  </paragraph>
  <paragraph>
    At the bottom of the panel, there are three check boxes. The <b>Add A Line Break</b> box will,
    if checked, adds a line break at the end of the inserted text. The second box, <b>Execute
    Scripts</b>, allows you to switch between execute and insert modes for scripted items. Indeed,
    some of the items held in the XTree are scripts. If you check the box, they will be
    normally executed (and this way act as macros). Otherwise, the script source will be inserted
    in your document. The third check box allows some items to surround the selection within the area.
    The top also provides a button called <b>Reload</b>. Clicking this button
    will simply reload the entire XTree from XML files. This is very useful when you want to
    load a new XInsert file without having to restart Jext.
  </paragraph>
  <paragraph>
    The most important component of the XInsert panel is the XTree. This tree contains a set
    of nodes which can be expanded to access other nodes or items. If you single-click on an item,
    its content will be inserted in your document. To expand/collapse a node, double-click it.
  </paragraph>

  <paragraph title="XInsert Files">
    You can add your own data to the <b>XTree</b> by creating new XInsert files. An XInsert file
    is a plain text file with the extension <b>.insert.xml</b> placed in the directory
    <b>&lt;home&gt;/.jext/xinsert</b>. Those files contain XML tags based on the <b>xinsert.dtd</b>
    document type definition which can be found in
    <b>&lt;jext home&gt;/lib/jext.jar!org/jext/</b>.
  </paragraph>
  <paragraph>
    Writing an XInsert file is quite easy. First you must declare the file as an XML document by
    placing this on the first line:
    <code>&lt;?xml version="1.0" encoding="UTF-8"?&gt;</code>
    Then, you must specify the XInsert DTD:
    <code>&lt;!DOCTYPE xinsert SYSTEM "xinsert.dtd"&gt;</code>
    Finally create the root tag:
    <code>&lt;xinsert&gt;&lt;/xinsert&gt;</code>
  </paragraph>
  <paragraph>
    You are now ready to create your own data node. Within the <b>&lt;xinsert&gt;</b> you can
    insert any number of <b>&lt;menu&gt;</b> tags you wish.
    <code>&lt;menu name="MENU_NAME" [modes="MODES"]&gt;&lt;/menu&gt;</code>
    Parameters between brackets [] are optional. If you set this attribute like this:
    <b>modes="java cc"</b> the menu will appear only when Java or C++ syntax colorizing modes
    are selected. This attribute works only with top parent menus. Nested submenus won't be
    affected by it.
  </paragraph>
  <paragraph>
    A menu tag can contain any number of other menu tags (to create nested submenus) as well
    as <b>&lt;item&gt;</b> tags:
    <code>
    &lt;item name="ITEM NAME" [type="plain|script|mixed"]&gt;ITEM CONTENTS&lt;/item&gt;
      &lt;br /&gt;
    &lt;/html&gt;
    </code>
    Parameters between brackets [] are considered optional. The <b>type</b> attribute can be used to define the item
    status. Specifying <i>plain</i> does the same thing as not writing the type attribute. Using <i>script</i>
    you can set the item as a script meant to be executed on a mouse click. Finally, the <i>mixed</i> value allows you to
    create items which can contain both scripts and plain text. Each script must be surrounded by two
    <b>%</b>. To enter a <b>%</b> as a normal character, type it twice: <b>%%</b>. The advantage of the mixed
    type is that the first value of stack created by the script will be inserted into the text.
    <b>ITEM CONTENTS</b> is the data which will be inserted/executed whenever you click on the item.
    Example of a mixed item:
    <code>&lt;item name="Mixed item" type="mixed"&gt;Hello %"Your name:" input% !&lt;/item&gt;</code>
    This item will, on click, prompt the user for its name and then insert the text "Hello name_entered !"
    in the text area. Another example:
    <code>&lt;item name="Mixed item 2" type="mixed"&gt;The current date is: %date%&gt;</code>
    This mixed item will display text and append the current date to it.
  </paragraph>
  <paragraph>
    You can see more examples by looking at the default XInsert files in the jext.jar archive file.
  </paragraph>
</xtiny-doc-page>

<!-- End of Jext documentation -->

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/xml-fr/jext-menus-file.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xtiny-doc-page SYSTEM "../dtd/xtiny-doc-page.dtd" >

<!--
  -
  - Jext documentation source document
  - Based on xtiny-doc DTD
  -
  - DTD:xtiny-doc and XSL:xtiny-doc
  - are (C)1999 Romain Guy
  -
  - Last updated: 09/30/2001 - 21:16:56
  -
  -->

<xtiny-doc-page author="Romain Guy"
           update="09/30/2001"
           name="Menu Fichier"
           title="Jext : Menu Fichier"
           prev="jext-menus.html"
           next="jext-menus-edit.html">

  <paragraph title="Présentation">
    Le menu <b>Fichier</b> contient toutes les fonctions ayant trait à la manipulation des fichiers.
  </paragraph>

  <menu title="Contenu">
    <item name="Nouveau">
      Crée un nouveau document utilisant le mode de coloration syntaxique en cours d'utilisation.
    </item>
    <item name="Nouveau Modèle">
      Crée un nouveau fichier depuis un modèle. Vous pouvez changer le répertoire d'accès aux modèles
      dans les options.
    </item>
    <item name="Effacer">
      Supprime tout le contenu du document.
    </item>
    <item name="Supprimer Fichier">
      Efface le fichier de votre disque dur. Jext vous demandera confirmation avant suppression.
    </item>
    <item name="Ouvrir">
      Ouvre un fichier existant en sélectionnant le mode de coloration à priori le plus approprié.
      Si vous ouvrez un fichier ZIP ou JAR, Jext lancer alors l'explorateur de ZIP dans lequel vous pourrez
      ouvrir un fichier directement depuis le fichier compressé.
    </item>
    <item name="Ouvrir Dans">
      Fonctionne de la même manière que la fonction "Ouvrir" mais ne crée pas de nouveau document. A la place,
      cette fonction remplace le document sélectionné par celui choisi.
    </item>
    <item name="Ouvrir URL">
      Ouvre un fichier désigné par son adresse internet.
    </item>
    <item name="Récents">
      Ce sous-menu contient la liste des fichiers ouverts récemment. Par défaut, ce sous-menu peut accueillir
      huit fichiers. Ceci peut cependant être configuré dans les options.
    </item>
    <item name="Effacer Récents">
      Supprime le contenu du menu "Récents". Ceci peut servir à masquer le nom des fichiers sur lesquels vous
      avez travaillé ou pour éviter d'ouvrir par accident un fichier stocké sur un périphérique de stockage
      amovible (CD-Rom, disquette, lecteur ZIP...).
    </item>
    <item name="Fermer">
      Ferme le document sélectionné. Si ce document a été modifié, Jext vous proposera de le sauvegarder.
      wether to save the document or not.
    </item>
    <item name="Fermer Tous">
      Ferme tous les documents ouverts dans le bureau courant.
    </item>
    <item name="Enregistrer">
      Enregistre le fichier. Si le document est nouveau (c'est à dire si il n'a pas encore été enregistré sur
      le disque dur), Jext fait appel à la fonction "Enregistrer Sous".
    </item>
    <item name="Enregistrer Tous">
      Enregistre tous les fichiers ouverts dans l'éditeur.
    </item>
    <item name="Enregistrer Sous">
      Permet d'enregistrer un nouveau document ou d'enregistrer un fichier sous un nom différent.
    </item>
    <item name="Imprimer">
      Imprime le document.
    </item>
    <item name="Nouvelle Fenêtre">
      Ouvre une nouvelle fenêtre Jext.
    </item>
    <item name="Ouvrir Dans Fenêtre">
      Crée une nouvelle fenêtre et ouvre un document en son sein.
    </item>
    <item name="Fermer Fenêtre">
      Ferme la fenêtre de Jext et quitte l'application si il ne reste plus aucune fenêtre ouverte. Si
      vos documents n'ont pas encore été sauvegardés, Jext vous proposera de le faire.
    </item>
    <item name="Quitter">
      Quitte Jext en fermant toutes les fenêtres actives.
    </item>
  </menu>
</xtiny-doc-page>

<!-- End of Jext documentation -->

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/xml-fr/jext-console.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xtiny-doc-page SYSTEM "../dtd/xtiny-doc-page.dtd" >

<!--
  -
  - Jext documentation source document
  - Based on xtiny-doc DTD
  -
  - DTD:xtiny-doc and XSL:xtiny-doc
  - are (C)1999 Romain Guy
  -
  - Last updated: 09/30/2001 - 21:44:50
  -
  -->

<xtiny-doc-page author="Romain Guy"
           update="09/30/2001"
           name="Jext : Console"
           title="Console"
           prev="jext-search.html"
           next="jext-xinsert.html">

  <paragraph title="Présentation">
    La console interne de Jext se comporte exactement comme la console de votre système (parfois appelée
    terminal). Ainsi, elle pourra être utilisée pour parcourir le disque dur, lancer des applications, etc...
  </paragraph>

  <paragraph title="Utiliser la console">
    Avant tout, sachez que la console est par défaut cachée. Vous devez appuyer sur <b>F8</b> ou l'activer
    dans les options en cochant l'option "Show top tabbed pane" de la section générale.
  </paragraph>
  <paragraph>
    Pour utiliser la console, cliquez simplement dessus et tapez votre commande, suivi de <b>ENTER</b> pour
    l'exécuter. La console propose de nombreuses commandes internes indépendantes du système, des variables
    (qui différent suivant le document en cours) ainsi que des touches spéciales.
  </paragraph>

  <paragraph title="Invite de la console">
    Jext laisse la possibilité à l'utilisateur de définir sa propre invite. L'invite par défaut est de la
    forme <b>nom_utilisateur@chemin &gt;</b>. Dans les options, vous avez la possivilité de changer ceci. Jext
    propose, en sus de cette invite, trois autres invites: Linux (<b>utilisateur@machine%</b>), Solaris
    (<b>machine%</b>) et DOS (<b>chemin &gt;</b>). Pour personnaliser l'invite, entrez n'importe quel texte
    dans le champ dédié. Dans votre invite, vous pourrez utilisez les variablez suivantes:
    <menu>
      <item name="$u">
        Inclut le nom de l'utilisateur dans l'invite
      </item>
      <item name="$h">
        Inclut le nom de l'hôte (machine) dans l'invite
      </item>
      <item name="$p">
        Inclut le chemin du répertoire courant
      </item>
      <item name="$$">
        Inclut le caractère '$' dans l'invite
      </item>
    </menu>
  </paragraph>

  <menu title="Commandes internes">
    <item name="help">
      Affiche l'aide de la console. Cette aide résume les commandes et les variables disponibles.
    </item>
    <item name="clear">
      Efface l'écran de la console.
    </item>
    <item name="cd">
      Cette commande sert à changer de répertoire. Les deux types de séparateurs / et \ sont acceptés.
      Vous pouvez également utiliser le caractère ~ qui représente le répertoire de l'utilisateur. Tapez
      <b>cd -help</b> pour plus d'informations.
    </item>
    <item name="exit">
      Quitte Jext.
    </item>
    <item name="home">
      Cette commande est un raccourci pour <b>cd &lt;chemin de jext&gt;</b>
    </item>
    <item name="ls">
      Cette fonction, bien connue des utilisateurs Un*x, est l'équivalent de la commande DOS 'dir'.
      Cette commande liste le contenu du répertoire courant. De nombreuses options sont acceptées. Vous
      pouvez en connaître l'usage en tapant <b>ls -help</b>. Notez que la commande <b>dir</b> fonctionnera
      de la même manière que celle-ci.
    </item>
    <item name="pwd">
      Affiche le chemin complet du répertoire courant.
    </item>
    <item name="file:nom_fichier">
      Permet d'ouvrir un fichier dans l'éditeur. Le nom de fichier peut contenir un chemin relatif
      (i.e file:../infos.txt) ou absolu (i.e file:/etc/.bashrc).
    </item>
    <item name="http://URL">
      Ouvre le contenu de l'adresse internet spécifiée.
    </item>
    <item name="run:nom_script">
      Lance l'exécution du script passé en paramètre. Pour obtenir plus d'informations à propos des scripts,
      veuillez consulter la section  <a href="jext-scripts.html">Scripts</a>.
    </item>
    <item name="eval:code">
      Exécute le code Python "code".
    </item>
  </menu>

  <paragraph title="Utilisation des variables">
    Si vous insérez une variable interne dans une commande console, la commande sera modifiée pour remplacer
    les variables par leur valeur avant exécution. Imaginons que vous ayiez ouvert le fichier Hello.java
    du répertoire /home/Gfx/java/hello et que vous souhaitiez le compiler. Même en faisant appel à la commande
    'cd' pour vous placer dans le susdit répertoire, vous ne serez pas en mesure de mener à bien la compilation.
    Ceci est dû à une limitation de Java. Mais vous pouvez contourner ce problème en utilisant les variables
    interne. Pour compiler le fichier, tapez donc la commande <b>javac $n/Hello.java</b>. Ensuite, pour
    lancer la classe Hello.class, tapez <b>java -classpath $n $e</b>. Les variables peuvent s'avérer très
    utiles dans de nombreux autres cas. Pour accéder au répertoire du fichier par exemple: <b>cd $n</b>
    ou pour effacer le fichier: <b>rm -f $f</b>.
  </paragraph>

  <menu title="Variables internes">
    <item name="$j">
      Répertoire de Jext.
    </item>
    <item name="$h">
      Répertoire utilisateur (/home/utilisateur sous Un*x, C:\Windows ou C:\Windows\Profiles\Utilisateur sous
      Windows).
    </item>
    <item name="$d">
      Répertoire courant.
    </item>
    <item name="$f">
      Fichier courant - sélectionné dans l'éditeur -, désigné par son chemin absolu.
    </item>
    <item name="$p">
      Nom du fichier sélectionné dans l'éditeur.
    </item>
    <item name="$e">
      Nom, sans extension, du fichier sélectionné dans l'éditeur.
    </item>
    <item name="$n">
      Répertoire du fichier sélectionné.
    </item>
    <item name="$s">
      Texte sélectionné dans l'éditeur.
    </item>
  </menu>

  <paragraph title="Touches">
    La console gère des touches pour en simplifier l'utilisation. En voici la liste:
  </paragraph>
  <menu>
    <item name="ESCAPE">
      Efface la ligne de commande en cours.
    </item>
    <item name="LEFT">
      Déplace le curseur vers la gauche.
    </item>
    <item name="RIGHT">
      Déplace le curseur vers la droite.
    </item>
    <item name="UP">
      Accède à la commande précedemment tapée (jusqu'à 25 en mémoire).
    </item>
    <item name="DOWN">
      Accède à la commande suivant dans l'historique des commandes tapées.
      Get next typed command from the history.
    </item>
    <item name="TAB">
      Complète le nom du fichier si une occurence est trouvée dans le répertoire courant. Par exemple,
      si vous êtes dans un répertoire contenant le fichier <b>jext-patch-2.8.0.3.zip</b>, vous pouvez
      taper simplement <b>jext-</b> et appuyer sur <b>TAB</b> pour que Jext complète le nom du fichier.
      Si plusieurs fichiers commençant par ce que vous avez tapé sont trouvés, Jext complète avec la plus
      grande partie commune.
    </item>
    <item name="S+TAB">
      Complète la commande si une occurence est trouvée dans l'historique. Si vous avez tapé par exemple
      <b>ls -rind</b> puis tapez seulement <b>ls -</b>, un appui sur <b>S+TAB</b> complètera la commande
      en <b>ls -rind</b>.
    </item>
    <item name="C+c">
      Copie le texte sélectionné dans le presse-papier.
    </item>
    <item name="C+d">
      Tue le processus courant. Si vous avez lancé une tâche qui semble avoir planté ou qui nécessite
      d'être tuée, appuyez sur ces touches.
    </item>
  </menu>
</xtiny-doc-page>

<!-- End of Jext documentation -->

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/xml-fr/jext-menus.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xtiny-doc-page SYSTEM "../dtd/xtiny-doc-page.dtd" >

<!--
  -
  - Jext documentation source document
  - Based on xtiny-doc DTD
  -
  - DTD:xtiny-doc and XSL:xtiny-doc
  - are (C)1999 Romain Guy
  -
  - Last updated: 09/30/2001 - 22:16:40
  -
  -->

<xtiny-doc-page author="Romain Guy"
           update="09/30/2001"
           name="Jext : Menus"
           title="Menus"
           prev="index.html"
           next="jext-menus-file.html">

  <paragraph title="Présentation">
    Les menus de Jext nécessitent quelques explications. Bien qu'ils soient similaires à ceux d'autres
    applications (Word, The GIMP, etc...), les menus de Jext possèdent une fonctionnalité intéressante
    que l'on retrouve usuellement dans Emacs/XEmacs... Voici donc comment ces menus fonctionnent.
  </paragraph>
  <paragraph>
    Chaque menu principal (Fichier, Edition...) contient des éléments (par exemple: "Sélectionner Tout"
    dans le menu "Edition") et éventuellement des sous-menus (par exemple, le sous-menu "Récents" du menu
    principal "Fichier"). Déroulez les menus principaux en cliquant dessus ou simplement en utilisant le
    raccourci clavier <b>Alt+LETTRE</b>, où LETTRE désigne la lettre soulignée dans le nom du menu. Vous
    pouvez également dérouler le menu "Fichier" en appuyant sur <b>F10</b>.
  </paragraph>
  <paragraph>
    Une fois que vous avez déroulé le menu désiré, sélectionnez l'élément de votre choix ou passez au dessus
    d'un sous-menu pour le dérouler à son tour. Vous remarquerez que certains éléments possèdent un texte
    bleuté sur leur droite. Ce texte rappelle le raccourci clavier associé à l'élément.
  </paragraph>

  <paragraph title="Eléments et raccourcis claviers">
    Les raccourcis claviers sont de la forme: <b>C+e</b>. Ce raccourci signifie: "maintenir appuyé la touche
    Control et presser e". Il existe deux autres modificateurs: <b>A</b> qui représente la touche <b>Alt</b>
    et <b>S</b> qui représente la touche <b>Shift</b> (Maj) ou <b>Meta</b>. Ces touches peuvent êtres
    combinées: <b>CA+s</b> signifie d'appuyer sur Control et Alt en même temps avant d'appuyer sur s.
  </paragraph>
  <paragraph>
    Il existe des raccourcis plus compliqués. Ceux-ci sont de la forme: <b>C+e C+m</b>. Un tel raccourci
    signifie: "maintenir appuyé sur Control, appuyer sur e, puis m, puis relâcher Control".
  </paragraph>

  <paragraph title="Actions répétées">
    Dans le menu édition, l'action "Supprimer Ligne" peut être activée en pressant <b>C+d</b>. Imaginez que
    vous souhaitiez effacer 10 lignes d'un coup... vous pourriez presser C+d dix fois mais il existe un moyen
    plus effiace...
  </paragraph>
  <paragraph>
    Ce moyen proposé par Jext est la combinaison <b>C+ENTER nombre raccourci</b>. Dans notre cas, la combinaison
    <b>C+ENTER 10 C+d</b> atteindra le résultat désiré ! Cette séquence se tape ainsi: appuyez sur Control,
    appuyez sur ENTER, relâchez Control, tapez 10, appuyez sur Control, appuyez sur d.
  </paragraph>
  <paragraph>
    Bien entendu, vous pouvez entrer n'importe quel nombre et utiliser n'importe quel raccourci clavier !
  </paragraph>
</xtiny-doc-page>

<!-- End of Jext documentation -->

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/xml-en/jext-menus-file.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xtiny-doc-page SYSTEM "../dtd/xtiny-doc-page.dtd" >

<!--
  -
  - Jext documentation source document
  - Based on xtiny-doc DTD
  -
  - DTD:xtiny-doc and XSL:xtiny-doc
  - are (C)1999 Romain Guy
  -
  - Last updated: 12/02/2001 - 22:16:09
  -
  -->

<xtiny-doc-page author="Romain Guy"
           update="12/02/2001"
           name="File Menu"
           title="Jext : File Menu"
           prev="jext-menus.html"
           next="jext-menus-edit.html">

  <paragraph title="Overview">
    The <b>File</b> menu contains features related to file management (open, save,
    new, etc.).
  </paragraph>

  <menu title="Contents">
    <item name="New File">
      Creates a new empty file with the current syntax colorizing mode enabled.
    </item>
    <item name="New From Template">
      Creates a new file from a selected template. You can set the templates directory in the options.
    </item>
    <item name="Clear File">
      Clears all text from the selected document.
    </item>
    <item name="Delete File">
      Erases the current file from your hard disk. You'll be prompted before deletion.
    </item>
    <item name="Open">
      Opens an existing file enabling the most appropriate syntax colorizing mode. If you open
      a ZIP or JAR file, Jext will open a ZipExplorer in which will prompt you to choose which
      packed file to open from the archive.
    </item>
    <item name="Open In Area">
      Works exactly like the Open function but does not create a new document in the interface. It
      replaces the selected document instead.
    </item>
    <item name="Open URL">
      Opens a file specified by its URL. This allows you to open a file from the Web or from
      your Intranet.
    </item>
    <item name="Recents">
      This submenu contains a list of recently opened files. By default it holds the eight most 
      recently opened files, but this can be configured in the Options pane.
    </item>
    <item name="Clear Recents">
      Flushes the contents of the Recents submenu. Use it to mask what you've been working on 
      or to prevent accidental access to recent files that no longer exist or aren't currently
      mounted (i.e. if they were opened from a removable device such as a CD-ROM or floppy disk).
    </item>
    <item name="Close">
      Closes the selected document. If this document was modified, Jext warns you and offers an 
      opportunity to save the document.
    </item>
    <item name="Close All">
      Closes all the open documents, asking to save any of them if they were modified.
    </item>
    <item name="Save">
      Saves the current document. If the current document is new (i.e. has not been opened from
      an existing file or has not been saved yet) Jext calls "Save As..."
    </item>
    <item name="Save All">
      Attempts to save all the opened documents.
    </item>
    <item name="Save As">
      Permits the current document to be saved with a different name.
    </item>
    <item name="Print">
      Prints the current document.
    </item>
    <item name="New Window">
      Creates a new Jext window.
    </item>
    <item name="Open In Window">
      Creates a new Jext window and opens an existing file in it, enabling the most appropriate
      syntax colorizing mode. Opening a ZIP or a JAR file initiates the same action as with the 
      normal Open command.
    </item>
    <item name="Close Window">
      Closes the current window and exits Jext if there are no remaining windows. If your work
      hasn't been saved yet, Jext asks you if you would like to save your changes before exiting.
    </item>
    <item name="Quit">
      Exits Jext by closing all its open windows and checking if your documents need to be
      saved or not.
    </item>
  </menu>
</xtiny-doc-page>

<!-- End of Jext documentation -->

=== youngkaneda/DemeterWatch/used-projects/jext-5.0/src/docs/xml-fr/jext-menus-jext.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xtiny-doc-page SYSTEM "../dtd/xtiny-doc-page.dtd" >

<!--
  -
  - Jext documentation source document
  - Based on xtiny-doc DTD
  -
  - DTD:xtiny-doc and XSL:xtiny-doc
  - are (C)1999 Romain Guy
  -
  - Last updated: 09/30/2001 - 20:16:50
  -
  -->

<xtiny-doc-page author="Romain Guy"
           update="09/30/2001"
           name="Menu Jext"
           title="Jext : Menu Jext"
           prev="jext-menus-plugins.html"
           next="jext-editor.html">

  <paragraph title="Présentation">
    Le menu <b>Jext</b> contient certaines fonctions spécifiques à Jext.
  </paragraph>

  <menu title="Contenu">
    <item name="A Propos...">
      Affiche la boîte de dialogue "A Propos" de l'application. Cette boîte de dialogue est extrêmement utile si vous
      désirez reporter un bug à l'auteur. Vous verrez en effet affichés le numéro de version de Jext, son nom de code
      ainsi que son numéro de sous-version. Le numéro de version du logiciel suit la convention suivante:
      majeur.mineur.révision (ex: 2.8.1). Le numéro de sous-version est bien plus important car plus précis. Celui-ci
      suit le format: majeur.mineur.révision.correction. Un bug sera corrigé plus rapidement si vous précisez ce
      numéro. Enfin, le nom de code apparaît entre les deux numéros précédents, entourés des signes <b>&lt;</b> et
      <b>&gt;</b>. Ce nom de code permet de distinguer les versions de développement non officielles. Là encore,
      veillez à bien préciser ce numéro lors de tout contact avec l'auteur ou des développeurs affiliés.
    </item>
    <item name="A Propos Des Plugins">
      Affiche la liste des plugins installés, leur numéro de version et le nom de leur(s) auteur(s).
      Cette fonction permet également d'activer/désactiver le chargement d'un plugin au démarrage de Jext sans
      avoir à le supprimer de votre disque dur. Pour désactiver un plugin, décochez simplement la case lui
      faisant face.
    </item>
  </menu>
</xtiny-doc-page>

<!-- End of Jext documentation -->
